basePath: /api/v1/documento
host: localhost
info:
  contact: {}
  description: Documento Service
  title: Documento Service API
  version: "1.0"
paths:
  /documento/add:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Arquivos para upload (múltiplos)
        in: formData
        name: arquivos
        required: true
        type: file
      produces:
      - application/json
      responses:
        "202":
          description: accepted
          schema:
            type: string
        "400":
          description: invalid request
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Criar documento
      tags:
      - Documento
  /health:
    get:
      description: Endpoint de healthcheck
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Retorna status da API
      tags:
      - health
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
